fun main() {

    val vanya = User(userId = 5,name = "Ваня", firstName = "Иванов")
    val petya = User(userId = 6,name = "Петя", firstName = "Петров")
    val vova = User(userId = 11,name = "Вова", firstName = "Орлов")
    val denis = User(userId = 22,name = "Денис",firstName = "Бурунов")
    val message1 = Message(chatId = 1,sender = vova,addressee = petya, text = "Привет")
    val message2 = Message(chatId = 2,messageId = 5,sender = vova,addressee = petya,text = "как дела?")
    val message3 = Message(chatId = 1,sender = vova,addressee = petya,text = "Нормально")
    val message4 = Message(chatId = 3, sender = denis,addressee = petya,text = "\uD83D\uDE00")
    val message5 = Message(messageId = 2, chatId = 1, sender = vova,addressee = vanya,text = "как дел?")
    val message6 = Message(messageId = 1, chatId = 1, sender = vova,addressee = vanya,text = "как делhjg?")
    val chat1 = Chat(createdBy = vanya, ownerBy = petya)
    val chat2 = Chat(chatId = 2,createdBy = vova, ownerBy = petya)
    val chat3 = Chat(chatId = 3, createdBy = petya, ownerBy = denis)
    val user1 = User(userId = 1, name = "Иван", firstName = "Иванов")
    val user2 = User(userId = 2, name = "Петр", firstName = "Петров")
    val user3 = User(userId = 3, name = "Александр", firstName = "Александров")
    val message11 = Message(chatId = 55, sender = user1, addressee = user2, text = "Hello")
    val message22 = Message(sender = user1, addressee = user3, text = "World")
    val service = Service()

    service.createMessage(message11)
    service.createMessage(message22)
    service.createMessage(message1)
    service.createMessage(message2)
    service.createMessage(message3)
    service.createMessage(message4)
    service.createMessage(message5)
    service.createMessage(message6)
    service.createMessage(message11)
    service.createMessage(message22)
    service.getChats()
//    println("*****************************")

//    println(service.getMessage(1,2, 2))
//    service.getChats()
    println(service.getMessage(1,1, 1))
//    println(service.getUnreadChatsCount(6))

}
